// Code generated by goctl. DO NOT EDIT.
package types

type RegisterReq struct {
	UserPhone string `json:"userPhone"`
	VeCode    string `json:"veCode"`
}

type RegisterByPhoneRep struct {
	UserPhone string `json:"userPhone"`
}

type LoginReq struct {
	PhoneOrEmail string `json:"phoneOrEmail"` // 手机号或者邮箱
	PassWord     string `json:"PassWord"`     // 用户密码，MD5加密
}

type UserInfoReq struct {
	UserId int64 `json:"userId"` // 用户id
}

type UserInfoResply struct {
	Code    int64         `json:"Code"`
	Message string        `json:"Message"`
	Data    *UserInfoItem `json:"Data"`
}

type RegisterByPhoneResply struct {
	Code    int64  `json:"Code"`
	Message string `json:"Message"`
	VeCode  string `json:"veCode"`
}

type UserInfoItem struct {
	UserID    int64  `json:"userId"`    // 用户id
	UserNick  string `json:"UserNick"`  // 用户昵称
	UserFace  string `json:"UserFace"`  // 用户头像地址
	UserSex   int64  `json:"UserSex"`   // 用户性别：0男，1女，2保密
	UserEmail string `json:"UserEmail"` // 用户邮箱
	UserPhone string `json:"UserPhone"` // 用户手机号
}

type CommonResply struct {
	Code    int64  `json:"Code"`
	Message string `json:"Message"`
	Data    string `json:"Data"`
}

type TokenResply struct {
	Code         int64  `json:"Code"`
	Message      string `json:"Message"`
	UserId       int64  `json:"userId"`
	AccessToken  string `json:"accessToken"`
	RefreshToken string `json:"refreshToken"`
}
